/**
 * OS-level service management — generate and enable a background daemon so the
 * bridge (monitor + webhook) survives reboots without openclaw or a shell.
 *
 *   Linux   → systemd user unit   (~/.config/systemd/user/weclaw-bridge.service)
 *   macOS   → launchd LaunchAgent (~/Library/LaunchAgents/com.weclaw.bridge.plist)
 *   Windows → scheduled task      (schtasks, runs on logon)
 *
 * All commands shell out to the OS-native tooling via spawnSync.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { resolveStateDir } from "../store/account.js";
import { Logger } from "../util/log.js";

export type Platform = "linux" | "darwin" | "win32";
export const SERVICE_NAME = "weclaw-bridge";

function detectPlatform(): Platform {
  switch (process.platform) {
    case "linux":
      return "linux";
    case "darwin":
      return "darwin";
    case "win32":
      return "win32";
    default:
      throw new Error(`unsupported platform: ${process.platform}`);
  }
}

/** Absolute path to the compiled CLI entry, resolved from this module. */
function cliEntryPath(): string {
  const here = path.dirname(fileURLToPath(import.meta.url)); // dist/service
  const pkgRoot = path.resolve(here, "..", "..");
  return path.join(pkgRoot, "dist", "cli.js");
}

export interface ServiceConfig {
  port?: string;
  host?: string;
  apiToken?: string;
  inboundWebhook?: string;
  /** Override the node binary (default: process.execPath). */
  nodeBin?: string;
}

function run(cmd: string, args: string[], log: Logger): { ok: boolean; stdout: string; stderr: string } {
  const res = spawnSync(cmd, args, { encoding: "utf-8" });
  if (res.status !== 0) {
    log.debug(`${cmd} ${args.join(" ")} → status ${res.status} stderr=${(res.stderr || "").trim()}`);
    return { ok: false, stdout: res.stdout || "", stderr: res.stderr || "" };
  }
  return { ok: true, stdout: res.stdout || "", stderr: res.stderr || "" };
}

// ── systemd (Linux user unit) ────────────────────────────────────────────────

function systemdUnitPath(): string {
  return path.join(os.homedir(), ".config", "systemd", "user", `${SERVICE_NAME}.service`);
}

function buildSystemdUnit(cfg: ServiceConfig): string {
  const env: string[] = [`Environment=WECLAW_STATE_DIR=${resolveStateDir()}`];
  if (cfg.port) env.push(`Environment=WECLAW_PORT=${cfg.port}`);
  if (cfg.host) env.push(`Environment=WECLAW_HOST=${cfg.host}`);
  if (cfg.apiToken) env.push(`Environment=WECLAW_API_TOKEN=${cfg.apiToken}`);
  if (cfg.inboundWebhook) env.push(`Environment=WECLAW_INBOUND_WEBHOOK=${cfg.inboundWebhook}`);
  const nodeBin = cfg.nodeBin || process.execPath;
  return `# Generated by weclaw — do not edit; run \`weclaw service install\` to regenerate.
[Unit]
Description=WeClawBridge (WeChat ClawBot iLink bridge)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${nodeBin} ${cliEntryPath()} start
Restart=on-failure
RestartSec=5
${env.join("\n")}

[Install]
WantedBy=default.target
`;
}

function systemdInstall(cfg: ServiceConfig, log: Logger): void {
  const unitPath = systemdUnitPath();
  fs.mkdirSync(path.dirname(unitPath), { recursive: true });
  fs.writeFileSync(unitPath, buildSystemdUnit(cfg), "utf-8");
  log.info(`wrote ${unitPath}`);

  // Enable lingering so the user unit runs before login / after reboot.
  const linger = run("loginctl", ["enable-linger", os.userInfo().username], log);
  if (!linger.ok) log.warn("loginctl enable-linger failed (may need sudo); the service may not run before you log in");

  run("systemctl", ["--user", "daemon-reload"], log);
  const enable = run("systemctl", ["--user", "enable", "--now", SERVICE_NAME], log);
  if (!enable.ok) {
    throw new Error(
      `systemctl enable failed: ${enable.stderr}\n  unit written to ${unitPath}\n  run: systemctl --user enable --now ${SERVICE_NAME}`,
    );
  }
  log.info("systemd user service enabled and started");
}

function systemdUninstall(log: Logger): void {
  run("systemctl", ["--user", "disable", "--now", SERVICE_NAME], log);
  const unitPath = systemdUnitPath();
  try {
    fs.unlinkSync(unitPath);
  } catch {
    // ignore
  }
  run("systemctl", ["--user", "daemon-reload"], log);
  log.info("systemd user service removed");
}

function systemdControl(action: "restart" | "stop" | "status", log: Logger): void {
  const res = run("systemctl", ["--user", action, SERVICE_NAME], log);
  if (action === "status") {
    process.stdout.write(res.stdout);
    if (!res.ok) process.stderr.write(res.stderr);
  }
}

// ── launchd (macOS) ──────────────────────────────────────────────────────────

function launchdPlistPath(): string {
  return path.join(os.homedir(), "Library", "LaunchAgents", "com.weclaw.bridge.plist");
}

function buildPlist(cfg: ServiceConfig): string {
  const nodeBin = cfg.nodeBin || process.execPath;
  const env: Record<string, string> = { WECLAW_STATE_DIR: resolveStateDir() };
  if (cfg.port) env.WECLAW_PORT = cfg.port;
  if (cfg.host) env.WECLAW_HOST = cfg.host;
  if (cfg.apiToken) env.WECLAW_API_TOKEN = cfg.apiToken;
  if (cfg.inboundWebhook) env.WECLAW_INBOUND_WEBHOOK = cfg.inboundWebhook;
  const envDict = Object.entries(env)
    .map(([k, v]) => `      <key>${k}</key><string>${escapeXml(v)}</string>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.weclaw.bridge</string>
  <key>ProgramArguments</key>
  <array>
    <string>${escapeXml(nodeBin)}</string>
    <string>${escapeXml(cliEntryPath())}</string>
    <string>start</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
${envDict}
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${escapeXml(path.join(resolveStateDir(), "weclaw.log"))}</string>
  <key>StandardErrorPath</key><string>${escapeXml(path.join(resolveStateDir(), "weclaw.err.log"))}</string>
</dict>
</plist>
`;
}

function escapeXml(s: string): string {
  return s.replace(/[<>&'"]/g, (c) =>
    c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === "&" ? "&amp;" : c === "'" ? "&apos;" : "&quot;",
  );
}

function launchdInstall(cfg: ServiceConfig, log: Logger): void {
  const plistPath = launchdPlistPath();
  fs.mkdirSync(path.dirname(plistPath), { recursive: true });
  // Unload first if present to avoid "service already loaded".
  run("launchctl", ["unload", plistPath], log);
  fs.writeFileSync(plistPath, buildPlist(cfg), "utf-8");
  log.info(`wrote ${plistPath}`);
  const load = run("launchctl", ["load", plistPath], log);
  if (!load.ok) throw new Error(`launchctl load failed: ${load.stderr}`);
  log.info("launchd agent loaded (will run at login & stay alive)");
}

function launchdUninstall(log: Logger): void {
  const plistPath = launchdPlistPath();
  run("launchctl", ["unload", plistPath], log);
  try {
    fs.unlinkSync(plistPath);
  } catch {
    // ignore
  }
  log.info("launchd agent removed");
}

function launchdStatus(log: Logger): void {
  const res = run("launchctl", ["list", "com.weclaw.bridge"], log);
  if (res.ok) process.stdout.write(res.stdout + "\n");
  else process.stdout.write("not loaded\n");
}

// ── Windows (scheduled task on logon) ─────────────────────────────────────────

function winInstall(cfg: ServiceConfig, log: Logger): void {
  const nodeBin = cfg.nodeBin || process.execPath;
  const entry = cliEntryPath().replace(/\//g, "\\");
  const nodeWin = nodeBin.replace(/\//g, "\\");
  const action = `"${nodeWin}" ${entry} start`;
  // schtasks /Create /SC ONLOGON runs the bridge whenever the user logs in.
  const envExports =
    `WECLAW_STATE_DIR=${resolveStateDir()}` +
    (cfg.port ? ` WECLAW_PORT=${cfg.port}` : "") +
    (cfg.host ? ` WECLAW_HOST=${cfg.host}` : "") +
    (cfg.apiToken ? ` WECLAW_API_TOKEN=${cfg.apiToken}` : "");
  // Wrap in a cmd that sets env then launches node.
  const cmd = `/C set ${envExports} & ${action}`;
  const res = spawnSync(
    "schtasks",
    ["/Create", "/TN", SERVICE_NAME, "/SC", "ONLOGON", "/RL", "LIMITED", "/F", "/TR", `cmd ${cmd}`],
    { encoding: "utf-8", shell: true },
  );
  if (res.status !== 0) {
    throw new Error(`schtasks /Create failed: ${res.stderr || res.stdout}\n  (run in a regular user terminal, not elevated)`);
  }
  // Start now.
  spawnSync("schtasks", ["/Run", "/TN", SERVICE_NAME], { encoding: "utf-8", shell: true });
  log.info("Windows scheduled task created (runs on logon)");
}

function winUninstall(log: Logger): void {
  spawnSync("schtasks", ["/Delete", "/TN", SERVICE_NAME, "/F"], { encoding: "utf-8", shell: true });
  log.info("Windows scheduled task removed");
}

function winStatus(): void {
  const res = spawnSync("schtasks", ["/Query", "/TN", SERVICE_NAME], { encoding: "utf-8", shell: true });
  if (res.status === 0) process.stdout.write(res.stdout);
  else process.stdout.write("not registered\n");
}

// ── dispatch ──────────────────────────────────────────────────────────────────

export function serviceInstall(cfg: ServiceConfig, log: Logger): void {
  const plat = detectPlatform();
  log.info(`platform: ${plat}`);
  if (plat === "linux") systemdInstall(cfg, log);
  else if (plat === "darwin") launchdInstall(cfg, log);
  else winInstall(cfg, log);
  process.stdout.write(`\n✅ installed as ${plat} service. Logs: ${path.join(resolveStateDir(), "weclaw*.log")}\n`);
}

export function serviceUninstall(log: Logger): void {
  const plat = detectPlatform();
  if (plat === "linux") systemdUninstall(log);
  else if (plat === "darwin") launchdUninstall(log);
  else winUninstall(log);
  process.stdout.write("\n✅ service removed\n");
}

export function serviceStatus(log: Logger): void {
  const plat = detectPlatform();
  if (plat === "linux") systemdControl("status", log);
  else if (plat === "darwin") launchdStatus(log);
  else winStatus();
}

export function serviceRestart(log: Logger): void {
  const plat = detectPlatform();
  if (plat === "linux") {
    systemdControl("restart", log);
    process.stdout.write("restarted\n");
  } else {
    // launchd/schtasks: stop+start via unload/load or Run.
    if (plat === "darwin") {
      run("launchctl", ["unload", launchdPlistPath()], log);
      run("launchctl", ["load", launchdPlistPath()], log);
      process.stdout.write("restarted\n");
    } else {
      spawnSync("schtasks", ["/End", "/TN", SERVICE_NAME], { encoding: "utf-8", shell: true });
      spawnSync("schtasks", ["/Run", "/TN", SERVICE_NAME], { encoding: "utf-8", shell: true });
      process.stdout.write("restarted\n");
    }
  }
}

export { detectPlatform };
